---
title: "HCZ-model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HCZ-model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(MetaRVM)
library(ggplot2)
```

We will create some sample input for this model run. (This data sets are also provided as part of the package).


```{r}
## Model initialization
sim_length <- 100

N_pop <- 6
pop_init <- data.frame(N = rep(NA, N_pop),
                       S0 = rep(NA, N_pop),
                       I0 = rep(NA, N_pop),
                       V0 = rep(NA, N_pop))

pop_init$N <- sample(1000:1500, N_pop)
pop_init$I0 <- sample(10:100, N_pop)
pop_init$V0 <- sample(1:10, N_pop)
pop_init$R0 <- sample(100:200, N_pop)
pop_init$S0 <- pop_init$N - pop_init$I0 - pop_init$V0

pop_zones <- pop_init

## Vaccine profile
tt <- seq(0, sim_length, by = 1)
nt <- length(tt)
vol <- sample(1:10, (nt-1)*N_pop, replace = TRUE)

vac_zones <- cbind(tt, rbind(pop_zones$V0, matrix(vol, nrow = nt-1)))
colnames(vac_zones) <- c("t", paste0("v", 1:N_pop))

## mixing matrix

m1 <- m2 <- m3 <- m4 <- matrix(NA, nrow = N_pop, ncol = N_pop)
diag(m1) <- round(runif(N_pop, min = 0.85, max = 0.92), 2)
diag(m2) <- 1
diag(m3) <- round(runif(N_pop, min = 0.7, max = 0.9), 2)
diag(m4) <- 1

for(ii in 1:N_pop){
  tmp <- runif(N_pop - 1)
  m1[ii, -ii] <- round(tmp * (1 - m1[ii, ii]) / sum(tmp), 2)
  m2[ii, -ii] <- 0
  m3[ii, -ii] <- round(tmp * (1 - m3[ii, ii]) / sum(tmp), 2)
  m4[ii, -ii] <- 0
}

m_weekday_day <- m1
m_weekday_night <- m2
m_weekend_day <- m3
m_weekend_night <- m4
```


```{r}
out <- meta_sim(N_pop = N_pop,
                ts = 0.7,
                tv = 0.2,
                S0 = pop_zones$S0,
                I0 = pop_zones$I0,
                P0 = pop_zones$N,
                R0 = pop_zones$R0,
                m_weekday_day = m_weekday_day,
                m_weekend_day = m_weekend_day,
                m_weekday_night = m_weekday_night,
                m_weekend_night = m_weekend_night,
                delta_t = 0.5,
                # tvac = vac_zones[, 1],
                vac_mat = as.matrix(vac_zones),
                dv = 50,
                de = 3,
                pea = 0.5,
                dp = 2,
                da = 5,
                ds = 2,
                psr = 0.5,
                dh = 3,
                phr = 0.9,
                dr = 50,
                ve = 0.5,
                nsteps = 100,
                is.stoch = 0,
                seed = NULL)

# head(out)
```
#### Aggregate level plot

```{r}
# covert to daily counts and long format
out$instance <- 1
long_out_daily <- daily_output(out, start_date = as.Date("2023-09-01"))
plot_metaRVM(long_out_daily,
                   conf_level = 90,
                   value_column = "total_value")
```
